export const customers = [
  {
    id: '001',
    shopName: 'Venettini Shoes Store',
    name: 'Danny Farago',
    address: '123 Main Street, New York, NY 10001',
  },
  {
    id: '002',
    shopName: 'Fashion Forward Boutique',
    name: 'Sarah Johnson',
    address: '456 Oak Avenue, Los Angeles, CA 90210',
  },
  {
    id: '003',
    shopName: 'Urban Style Shop',
    name: 'Mike Chen',
    address: '789 Pine Road, Chicago, IL 60601',
  },
  {
    id: '004',
    shopName: 'Classic Footwear Co.',
    name: 'Emma Wilson',
    address: '321 Elm Street, Miami, FL 33101',
  },
  {
    id: '005',
    shopName: 'Step Up Footwear',
    name: 'Liam Smith',
    address: '987 Maple Street, Seattle, WA 98101',
  },
  {
    id: '006',
    shopName: 'Elegance Boutique',
    name: 'Olivia Brown',
    address: '654 Cedar Avenue, Austin, TX 73301',
  },
  {
    id: '007',
    shopName: 'Trendy Soles',
    name: 'Noah Davis',
    address: '213 Birch Lane, Denver, CO 80201',
  },
  {
    id: '008',
    shopName: 'Chic Streetwear',
    name: 'Ava Martinez',
    address: '778 Spruce Street, San Francisco, CA 94101',
  },
  {
    id: '009',
    shopName: 'The Shoe District',
    name: 'James Anderson',
    address: '1900 Broadway, Nashville, TN 37203',
  },
  {
    id: '010',
    shopName: 'NextGen Kicks',
    name: 'Isabella Thomas',
    address: '510 Market Street, Philadelphia, PA 19103',
  },
  {
    id: '011',
    shopName: 'Metro Shoe Co.',
    name: 'Benjamin Taylor',
    address: '11 Grand Ave, Phoenix, AZ 85001',
  },
  {
    id: '012',
    shopName: 'Style & Sole',
    name: 'Charlotte Moore',
    address: '702 Walnut Blvd, Portland, OR 97201',
  },
  {
    id: '013',
    shopName: 'Couture Kicks',
    name: 'Elijah Harris',
    address: '1601 Vine Street, Cincinnati, OH 45202',
  },
  {
    id: '014',
    shopName: 'Footwear Fanatics',
    name: 'Amelia Clark',
    address: '300 Main Street, Salt Lake City, UT 84101',
  },
  {
    id: '015',
    shopName: 'Shoe Stop',
    name: 'Lucas Lewis',
    address: '98 Liberty Avenue, Orlando, FL 32801',
  },
  {
    id: '016',
    shopName: 'Luxe Looks',
    name: 'Mia Walker',
    address: '432 Park Ave, New York, NY 10022',
  },
  {
    id: '017',
    shopName: 'Shoe Utopia',
    name: 'Henry Robinson',
    address: '950 Sunset Blvd, Los Angeles, CA 90028',
  },
  {
    id: '018',
    shopName: 'Vogue Vibes',
    name: 'Harper White',
    address: '345 Queen Street, Honolulu, HI 96813',
  },
  {
    id: '019',
    shopName: 'Sole Society',
    name: 'Jack Hall',
    address: '27 Oak Street, Atlanta, GA 30303',
  },
  {
    id: '020',
    shopName: 'Strut Fashion',
    name: 'Evelyn Allen',
    address: '250 Rose Street, Minneapolis, MN 55401',
  },
  {
    id: '021',
    shopName: 'Footwear Express',
    name: 'Alexander Young',
    address: '1001 King Street, Detroit, MI 48201',
  },
  {
    id: '022',
    shopName: 'Dapper Steps',
    name: 'Sofia Hernandez',
    address: '872 River Road, New Orleans, LA 70112',
  },
  {
    id: '023',
    shopName: 'FootTrendz',
    name: 'Sebastian King',
    address: '144 North Ave, Kansas City, MO 64106',
  },
  {
    id: '024',
    shopName: 'Premier Soles',
    name: 'Ella Scott',
    address: '230 West Street, Raleigh, NC 27601',
  },
  {
    id: '025',
    shopName: 'Stride City',
    name: 'Daniel Green',
    address: '421 Hilltop Road, Albuquerque, NM 87101',
  },
  {
    id: '026',
    shopName: 'Chroma Styles',
    name: 'Luna Adams',
    address: '1055 Garden Blvd, Tampa, FL 33602',
  },
  {
    id: '027',
    shopName: 'Echo Shoes',
    name: 'Matthew Baker',
    address: '62 Willow Street, Boston, MA 02108',
  },
  {
    id: '028',
    shopName: 'Urban Stepz',
    name: 'Scarlett Nelson',
    address: '455 Ocean Drive, Virginia Beach, VA 23451',
  },
  {
    id: '029',
    shopName: 'The Footwear Lounge',
    name: 'David Perez',
    address: '312 Lincoln Road, Miami Beach, FL 33139',
  },
  {
    id: '030',
    shopName: 'Edge Streetwear',
    name: 'Chloe Campbell',
    address: '801 Mission Blvd, San Diego, CA 92109',
  },
  {
    id: '031',
    shopName: 'Shoe Canvas',
    name: 'Joseph Mitchell',
    address: '77 2nd Street, San Jose, CA 95113',
  },
  {
    id: '032',
    shopName: 'Downtown Threads',
    name: 'Victoria Rogers',
    address: '540 Liberty Street, Columbus, OH 43215',
  },
  {
    id: '033',
    shopName: 'Bold Footwear',
    name: 'Andrew Reed',
    address: '65 Grandview Ave, Pittsburgh, PA 15211',
  },
  {
    id: '034',
    shopName: 'Urban Vogue Shoes',
    name: 'Grace Cox',
    address: '180 Lake Shore Dr, Milwaukee, WI 53202',
  },
];

export const filterOptions = [
  { id: 'storeName', label: 'Store Name', icon: '🏬' },
  { id: 'email', label: 'Email', icon: '📧' },
  { id: 'phone', label: 'Phone', icon: '📞' },
];

