import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  leftSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  logoContainer: {
    marginRight: 16,
  },
  logo: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoShape: {
    position: 'relative',
    width: 32,
    height: 24,
  },
  logoBoat: {
    position: 'absolute',
    bottom: 0,
    left: 4,
    width: 24,
    height: 8,
    backgroundColor: '#1E40AF',
    borderRadius: 12,
  },
  logoSail: {
    position: 'absolute',
    top: 0,
    left: 8,
    width: 16,
    height: 16,
    backgroundColor: '#3B82F6',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 4,
    borderBottomLeftRadius: 4,
  },
  logoFlag: {
    position: 'absolute',
    top: 2,
    right: 8,
    width: 6,
    height: 4,
    backgroundColor: '#DC2626',
    borderRadius: 1,
  },
  logoWaves: {
    position: 'absolute',
    bottom: -8,
    left: 0,
    right: 0,
    height: 6,
  },
  wave: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: '#60A5FA',
    borderRadius: 1,
  },
  wave2: {
    bottom: 3,
    backgroundColor: '#93C5FD',
    opacity: 0.7,
  },
  greeting: {
    fontSize: 20,
    fontWeight: '500',
    color: '#6B7280',
  },
  rightSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  iconButton: {
    padding: 4,
  },
  notificationContainer: {
    position: 'relative',
  },
  bellIcon: {
    fontSize: 24,
    color: '#6B7280',
  },
  notificationBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#DC2626',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  notificationCount: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  profileAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
});