export const orders = [
    {
        poNumber: "705126",
        productCategory: "MENS FOOTWEAR / KIRYAS JOEL SHOES",
        productName: "Sandals",
        customerName: "CHAIM SCHNITZER",
        date: "03-06-2025",
        shippingAddress: "51 FOREST RD MONROE NY, 10950",
        status: "Pending",
    },
    {
        poNumber: "705127",
        productCategory: "WOMENS FOOTWEAR / BROOKLYN SHOES",
        productName: "Comfort Sandals",
        customerName: "SARAH LEVI",
        date: "04-06-2025",
        shippingAddress: "102 KINGS HWY BROOKLYN NY, 11223",
        status: "Shipped",
    },
    {
        poNumber: "705128",
        productCategory: "CHILDREN FOOTWEAR / QUEENS SHOES",
        productName: "Kids Sneakers",
        customerName: "DAVID COHEN",
        date: "05-06-2025",
        shippingAddress: "88 MAIN ST FLUSHING NY, 11355",
        status: "Delivered",
    },
    {
        poNumber: "705129",
        productCategory: "MENS FOOTWEAR / MONSEY SHOES",
        productName: "Dress Shoes",
        customerName: "MOSHE GOLDSTEIN",
        date: "06-06-2025",
        shippingAddress: "19 CEDAR LN MONSEY NY, 10952",
        status: "Cancelled",
    },
    {
        poNumber: "705130",
        productCategory: "WOMENS FOOTWEAR / LAKEWOOD SHOES",
        productName: "Heeled Boots",
        customerName: "RACHEL GREENBERG",
        date: "07-06-2025",
        shippingAddress: "25 OCEAN AVE LAKEWOOD NJ, 08701",
        status: "Pending",
    },
];
